
name: Build NitroEdit

on: [push]

jobs:
  NitroEdit:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Build
      run: make -C NitroEdit

    - uses: actions/upload-artifact@master
      with:
        name: NitroEdit
        path: NitroEdit/NitroEdit.nds